USE [master]
GO
/****** Object:  Database [Todo]    Script Date: 1/3/2022 5:10:16 PM ******/
CREATE DATABASE [Todo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Todo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Todo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Todo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Todo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Todo] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Todo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Todo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Todo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Todo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Todo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Todo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Todo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Todo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Todo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Todo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Todo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Todo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Todo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Todo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Todo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Todo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Todo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Todo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Todo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Todo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Todo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Todo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Todo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Todo] SET RECOVERY FULL 
GO
ALTER DATABASE [Todo] SET  MULTI_USER 
GO
ALTER DATABASE [Todo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Todo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Todo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Todo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Todo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Todo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Todo', N'ON'
GO
ALTER DATABASE [Todo] SET QUERY_STORE = OFF
GO
USE [Todo]
GO
/****** Object:  Table [dbo].[Todo]    Script Date: 1/3/2022 5:10:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Todo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SerialNo] [int] NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](200) NULL,
	[IsCompleted] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Todo] SET  READ_WRITE 
GO
